[config]
  schemaVersion="0.0.1"

[general]
  repository="https://thunderstore.io"

[package]
  containsNsfwContent=false
  description        ="A library for adding new contracts"
  name               ="ContractQueen"
  namespace          ="Robyn"
  websiteUrl         ="https://github.com/RobynLlama/ContractQueen"

  [package.dependencies]
    BepInEx-BepInExPack="5.4.2304"
    Robyn-FrogDataLib  ="0.2.0"
    darmuh-YapLocalizer="0.1.2"

[build]
  icon  ="../../icon.png"
  outdir="../../artifacts/thunderstore/"
  readme="../../README.md"

  [[build.copy]]
    source="../../artifacts/bin/ContractQueen/release/dev.mamallama.contractqueen.dll"
    target="plugins/"

  [[build.copy]]
    source="../../CHANGELOG.md"
    target="/"

  [[build.copy]]
    source="../../LICENSE"
    target="/"

    # The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
  # See communities at:
  # https://thunderstore.io/api/experimental/community/
  communities=["yapyap"]

  [publish.categories]
    # See categories at:
    # https://thunderstore.io/api/experimental/community/yapyap/category/
    yapyap=["mods"]
